DROP TABLE IF EXISTS motherboard;
	
/*!40101 SET NAMES utf8 */;

CREATE TABLE motherboard (
	`id` int(11) null auto_increment,
	`company` varchar(20) default null,
	`model` varchar(30) default null,
	`rev` decimal(2,1) unsigned default null,
	`chipset` varchar(50) default null,
	`C_compnay` varchar(10) default null,
	`C_socket` varchar(20) default null,
	`C_supp_detail_1` varchar(100) default null,
	`C_supp_detail_2` varchar(100) default null,
	`C_supp_detail_3` varchar(100) default null,
	`C_supp_detail_4` varchar(100) default null,
	`C_supp_detail_5` varchar(100) default null,
	`M_ddr2_slot` tinyint(2) unsigned default null,
	`M_ddr2_upTo` tinyint(2) unsigned default null,
	`M_ddr2_bus` varchar(100) default null,
	`M_ddr2_comment` varchar(500) default null,
	`M_ddr3_slot` tinyint(2) unsigned default null,
	`M_ddr3_upTo` tinyint(2) unsigned default null,
	`M_ddr3_bus` varchar(100) default null,
	`M_ddr3_comment` varchar(500) default null,
	`M_upTo` tinyint(2) unsigned default null,
	`M_architecture` varchar(20) default null,
	`M_supp_unbuffered-ecc_memory_modules` varchar(10) default null,
	`M_supp_non-ecc_memory_modules` varchar(10) default null,
	`M_supp_xmp_memory_modules` varchar(10) default null,
	`M_supp_xmp_memory_modules_comment` varchar(500) default null,
	`A_chip` varchar(50) default null,
	`A_channel` varchar(20) default null,
	`A_hd_audio` varchar(10) default null,
	`A_supp_spdif_out` varchar(10) default null,
	`A_supp_dolby®_home_theater` varchar(10) default null,
	`A_supp_eax®_advanced_hd™_5.0` varchar(10) default null,
	`A_supp_x-fi_xtreme_fidelity®` varchar(10) default null,
	`L_chip_1` varchar(50) default null,
	`L_chip_2` varchar(50) default null,
	`Wireless Communication module_detail_1` varchar(50) default null,
	`Wireless Communication module_detail_2` varchar(50) default null,
	`ES_pcie_x16_@16x_num` tinyint(2) unsigned default null,
	`ES_pcie_x16_@16x_name` varchar(40) default null,
	`ES_pcie_x16_@16x_comment` varchar(300) default null,
	`ES_pcie_x16_@8x_num` tinyint(2) unsigned default null,
	`ES_pcie_x16_@8x_name` varchar(40) default null,
	`ES_pcie_x16_@8x_comment` varchar(300) default null,
	`ES_pcie_x16_@4x_num` tinyint(2) unsigned default null,
	`ES_pcie_x16_@4x_name` varchar(40) default null,
	`ES_pcie_x16_@4x_comment` varchar(300) default null,
	`ES_pcie_x16_comment` varchar(300) default null,
	`ES_pcie_x1_num` tinyint(2) unsigned default null,
	`ES_pcie_x1_comment` varchar(300) default null,
	`ES_pci_num` tinyint(2) unsigned default null,
	`Multi-Graphics Technology` varchar(100) default null,
	`OG_IGP_d-sub_port` tinyint(2) unsigned default null,
	`OG_IGP_dvi-d_port_num` tinyint(2) unsigned default null,
	`OG_IGP_dvi-d_port_max_res` varchar(20) default null,
	`OG_IGP_dvi-d_port_comment` varchar(400) default null,
	`OG_IGP_hdmi_port_num` tinyint(2) unsigned default null,
	`OG_IGP_hdmi_port_max_res` varchar(20) default null,
	`OG_IGP_displayport_num` tinyint(2) unsigned default null,
	`OG_IGP_displayport_max_res` varchar(20) default null,
	`OG_chip-2_name` varchar(50) default null,
	`OG_chip-2_thunderbolt_port_num` tinyint(2) unsigned default null,
	`OG_chip-2_thunderbolt_port_ver` varchar(40) default null,
	`OG_chip-2_thunderbolt_port_max_res` varchar(20) default null,
	`OG_chip-2_thunderbolt_port_supp_mini-displayport` varchar(10) default null,
	`OG_chip-2_thunderbolt_port_supp_thunderbolt_monitor(s)` varchar(10) default null,
	`OG_chip-2_thunderbolt_port_comment` varchar(400) default null,
	`SI_chip-1_sata_6Gb/s_connector_num` tinyint(2) unsigned default null,
	`SI_chip-1_sata_6Gb/s_connector_ver` varchar(20) default null,
	`SI_chip-1_sata_6Gb/s_connector_upTo` varchar(20) default null,
	`SI_chip-1_sata_3Gb/s_connector_num` tinyint(2) unsigned default null,
	`SI_chip-1_sata_3Gb/s_connector_ver` varchar(20) default null,
	`SI_chip-1_sata_3Gb/s_connector_upTo` varchar(20) default null,
	`SI_chip-1_raid_supp` varchar(50) default null,
	`SI_chip-1_raid_supp_comment` varchar(500) default null,
	`SI_chip-1_sas_3Gb/s_connector_num` tinyint(2) unsigned default null,
	`SI_chip-1_sas_3Gb/s_connector_ver` varchar(20) default null,
	`SI_chip-1_sas_3Gb/s_connector_upTo` varchar(20) default null,
	`SI_chip-1_sas_3Gb/s_connector_raid_supp` varchar(50) default null,
	`SI_chip-2` varchar(50) default null,
	`SI_chip-2_sata_6Gb/s_connector_num` tinyint(2) unsigned default null,
	`SI_chip-2_sata_6Gb/s_connector_ver` varchar(20) default null,
	`SI_chip-2_sata_6Gb/s_connector_upTo` varchar(20) default null,
	`SI_chip-2_esata_6Gb/s_connector_num` tinyint(2) unsigned default null,
	`SI_chip-2_esata_6Gb/s_connector_ver` varchar(50) default null,
	`SI_chip-2_esata_6Gb/s_connector_upTo` varchar(20) default null,
	`SI_chip-2_raid_supp` varchar(50) default null,
	`SI_chip-2_raid_supp_comment` varchar(500) default null,
	`USB_chip-1_upTo` tinyint(2) unsigned default null,
	`USB_chip-1_ver` varchar(20) default null,
	`USB_chip-1_ports on the back panel` tinyint(2) unsigned default null,
	`USB_chip-1_ports available through the internal USB headers` tinyint(2) unsigned default null,
	`USB_chip-2` varchar(50) default null,
	`USB_chip-2_upTo` tinyint(2) unsigned default null,
	`USB_chip-2_ver` varchar(20) default null,
	`USB_chip-2_ports on the back panel` tinyint(2) unsigned default null,
	`USB_chip-2_ports available through the internal USB headers` tinyint(2) unsigned default null,
	`USB_chip-3` varchar(50) default null,
	`USB_chip-3_upTo` tinyint(2) unsigned default null,
	`USB_chip-3_ver` varchar(20) default null,
	`USB_chip-3_ports on the back panel` tinyint(2) unsigned default null,
	`USB_chip-3_ports available through the internal USB headers` tinyint(2) unsigned default null,
	`IEEE 1394_chip_name` varchar(50) default null,
	`IEEE 1394_chip_upTo` tinyint(2) default null,
	`IEEE 1394_chip_ver` varchar(20) default null,
	`IEEE 1394_chip_ports on the back panel` tinyint(2) default null,
	`IEEE 1394_chip_ports available through the internal header` tinyint(2) default null,
	`IIOC_24-pin ATX main power connector` tinyint(2) unsigned default null,
	`IIOC_8-pin ATX 12V power connector` tinyint(2) unsigned default null,
	`IIOC_4-pin ATX 12V power connector` tinyint(2) unsigned default null,
	`IIOC_PCIe power connector` tinyint(2) unsigned default null,
	`IIOC_SATA 6Gb/s connector` tinyint(2) unsigned default null,
	`IIOC_SATA 3Gb/s connector` tinyint(2) unsigned default null,
	`IIOC_mSATA connector` tinyint(2) unsigned default null,
	`IIOC_CPU fan header` tinyint(2) unsigned default null,
	`IIOC_system fan header` tinyint(2) unsigned default null,
	`IIOC_front panel header` tinyint(2) unsigned default null,
	`IIOC_front panel audio header` tinyint(2) unsigned default null,
	`IIOC_S/PDIF Out header` tinyint(2) unsigned default null,
	`IIOC_USB 3.0/2.0 header` tinyint(2) unsigned default null,
	`IIOC_USB 2.0/1.1 header` tinyint(2) unsigned default null,
	`IIOC_IEEE 1394a header` tinyint(2) unsigned default null,
	`IIOC_serial port header` tinyint(2) unsigned default null,
	`IIOC_parallel port` tinyint(2) unsigned default null,
	`IIOC_chassis intrusion header` tinyint(2) unsigned default null,
	`IIOC_digital microphone header` tinyint(2) unsigned default null,
	`IIOC_speaker header` tinyint(2) unsigned default null,
	`IIOC_AIO speaker header` tinyint(2) unsigned default null,
	`IIOC_LVDS drive voltage header` tinyint(2) unsigned default null,
	`IIOC_LVDS connector` tinyint(2) unsigned default null,
	`IIOC_flat panel display power header` tinyint(2) unsigned default null,
	`IIOC_flat panel display power connector` tinyint(2) unsigned default null,
	`IIOC_flat panel display switch header` tinyint(2) unsigned default null,
	`IIOC_backlight switch header` tinyint(2) unsigned default null,
	`IIOC_WIFI activity indicator LED header` tinyint(2) unsigned default null, 
	`IIOC_Clear CMOS jumper` tinyint(2) unsigned default null,
	`IIOC_Trusted Platform Module (TPM) header` tinyint(2) unsigned default null, 
	`IIOC_onboard voltage measurement module` tinyint(2) unsigned default null,
	`IIOC_Voltage Measurement Points` tinyint(2) unsigned default null,
	`IIOC_power button` tinyint(2) unsigned default null,
	`IIOC_reset button` tinyint(2) unsigned default null,
	`IIOC_Clear CMOS button` tinyint(2) unsigned default null,
	`IIOC_Gear button` tinyint(2) unsigned default null,
	`IIOC_CPU BCLK Down button` tinyint(2) unsigned default null,
	`IIOC_CPU BCLK Up button` tinyint(2) unsigned default null,
	`IIOC_CPU Ratio Down button` tinyint(2) unsigned default null,
	`IIOC_CPU Ratio Up button` tinyint(2) unsigned default null,
	`IIOC_BIOS Switch` tinyint(2) unsigned default null,
	`IIOC_LN2 switch` tinyint(2) unsigned default null,
	`BPC_PS/2 keyboard port` tinyint(2) unsigned default null,
	`BPC_PS/2 mouse port` tinyint(2) unsigned default null,
	`BPC_PS/2 keyboard/mouse port` tinyint(2) unsigned default null,
	`BPC_CPU overclocking button` tinyint(2) unsigned default null,
	`BPC_BIOS switch button` tinyint(2) unsigned default null,
	`BPC_Clear CMOS button` tinyint(2) unsigned default null,
	`BPC_IEEE 1394 port` tinyint(2) unsigned default null,
	`BPC_IEEE 1394a port` tinyint(2) unsigned default null,
	`BPC_USB 3.0/2.0 port` tinyint(2) unsigned default null,
	`BPC_USB 2.0/1.1 port` tinyint(2) unsigned default null,
	`BPC_eSATA/USB Combo connector` tinyint(2) unsigned default null,
	`BPC_eSATA 6Gb/s connector` tinyint(2) unsigned default null,
	`BPC_RJ-45 port` tinyint(2) unsigned default null,
	`BPC_parallel port` tinyint(2) unsigned default null,
	`BPC_serial port` tinyint(2) unsigned default null,
	`BPC_optical S/PDIF Out connector` tinyint(2) unsigned default null,
	`BPC_coaxial S/PDIF Out connector` tinyint(2) unsigned default null,
	`BPC_DC-In power connector` tinyint(2) unsigned default null,
	`BPC_audio jacks` tinyint(2) unsigned default null,
	`BPC_audio jacks_detail` varchar(200) default null,
	`BPC_D-Sub port` tinyint(2) unsigned default null,
	`BPC_DVI-D port` tinyint(2) unsigned default null,
	`BPC_HDMI port` tinyint(2) unsigned default null,
	`BPC_DisplayPort` tinyint(2) unsigned default null,
	`I/O Controller` varchar(50) default null,
	`HWM_System voltage detection` varchar(10) default null,
	`HWM_CPU/System temperature detection` varchar(10) default null,
	`HWM_CPU/System fan speed detection` varchar(10) default null,
	`HWM_CPU overheating warning` varchar(10) default null,
	`HWM_CPU/System fan fail warning` varchar(10) default null,
	`HWM_CPU/System fan speed control` varchar(10) default null,
	`HWM_comment` varchar(500) default null,
	`BIOS_detail_1` varchar(50) default null,
	`BIOS_detail_2` varchar(50) default null,
	`BIOS_detail_3` varchar(50) default null,
	`BIOS_detail_4` varchar(50) default null,
	`BIOS_detail_5` varchar(50) default null,
	`UF_supp_@BIOS` varchar(10) default null,
	`UF_supp_Q-Flash` varchar(10) default null,
	`UF_supp_Xpress BIOS Rescue` varchar(10) default null,
	`UF_supp_Download Center` varchar(10) default null,
	`UF_supp_Xpress Install` varchar(10) default null,
	`UF_supp_Xpress Recovery2` varchar(10) default null,
	`UF_supp_EasyTune` varchar(10) default null,
	`UF_supp_Smart 6™` varchar(10) default null,
	`UF_supp_eXtreme Hard Drive (X.H.D)` varchar(10) default null,
	`UF_supp_ON/OFF Charge` varchar(10) default null,
	`UF_supp_Cloud OC` varchar(10) default null,
	`UF_supp_3TB+ Unlock` varchar(10) default null,
	`UF_supp_TouchBIOS` varchar(10) default null,
	`UF_supp_Q-Share` varchar(10) default null,
	`UF_supp_3D Power` varchar(10) default null,
	`UF_comment` varchar(500) default null,
	`Bundle Software` varchar(500) default null,
	`Operating System` varchar(200) default null,
	`Form Factor` varchar(50) default null,
	`Remark_1` varchar(500) default null,
	`Remark_2` varchar(500) default null,
	`img_1` varchar(50) default null,
	`img_2` varchar(50) default null,
	`img_3` varchar(50) default null,
	`img_4` varchar(50) default null,
	`img_5` varchar(50) default null,
	`img_6` varchar(50) default null,
	`img_7` varchar(50) default null,
	`img_8` varchar(50) default null,
	`img_9` varchar(50) default null,
	`img_10` varchar(50) default null,
	`img_brand` varchar(50) default null,
	`price` varchar(10),
	primary key (id)
);

INSERT INTO motherboard VALUES(
	/* id */ null,
	/* company */ 'GIGABYTE',
	/* model */ 'GA-X79-UP4',
	/* rev */ 1.1,
	/* chipset */ 'Intel&reg; X79 Express Chipset',
	/* C_compnay */ 'Intel',
	/* C_socket */ '2011',
	/* C_supp_detail_1 */ 'Support for Intel&reg; Core&trade; i7 processors in the LGA2011 package',
	/* C_supp_detail_2 */ 'L3 cache varies with CPU',
	/* C_supp_detail_3 */ null,
	/* C_supp_detail_4 */ null,
	/* C_supp_detail_5 */ null,
	/* M_ddr2_slot */ null,
	/* M_ddr2_upTo */ null,
	/* M_ddr2_bus */ null,
	/* M_ddr2_comment */ null,
	/* M_ddr3_slot */ 8,
	/* M_ddr3_upTo */ 64,
	/* M_ddr3_bus */ '2133/1866/1600/1333/1066',
	/* M_ddr3_comment */ 'Due to a Windows 32-bit operating system limitation, when more than 4 GB of physical memory is installed, the actual memory size displayed will be less than the size of the physical memory installed.',
	/* M_upTo */ null,
	/* M_architecture */ '4 channel',
	/* M_supp_unbuffered-ecc_memory_modules */ null,
	/* M_supp_non-ecc_memory_modules */ 'YES',
	/* M_supp_xmp_memory_modules */ 'YES',
	/* M_supp_xmp_memory_modules_comment */ null,
	/* A_chip */ 'Realtek ALC892 codec',
	/* A_channel */ '2/4/5.1/7.1',
	/* A_hd_audio */ 'YES',
	/* A_supp_spdif_out */ 'YES',
	/* A_supp_dolby®_home_theater */ null,
	/* A_supp_eax®_advanced_hd™_5.0 */ null,
	/* A_supp_x-fi_xtreme_fidelity® */ null,
	/* L_chip_1 */ 'Intel GbE LAN chip (10/100/1000 Mbit)',
	/* L_chip_2 */ null,
	/* Wireless Communication module_detail_1 */ null,
	/* Wireless Communication module_detail_2 */ null,
	/* ES_pcie_x16_@16x_num */ 2,
	/* ES_pcie_x16_@16x_name */ 'PCIEX16_1, PCIEX16_2',
	/* ES_pcie_x16_@16x_comment */ 'For optimum performance, if only one PCI Express graphics card is to be installed, be sure to install it in the PCIEX16 slot.',
	/* ES_pcie_x16_@8x_num */ 2,
	/* ES_pcie_x16_@8x_name */ 'PCIEX8_1, PCIEX8_2',
	/* ES_pcie_x16_@8x_comment */ 'The PCIEX8_2 slot shares bandwidth with the PCIEX16_2 slot. When the PCIEX8_2 slot is populated, the PCIEX16_2 slot will operate at up to x8 mode.',
	/* ES_pcie_x16_@4x_num */ null,
	/* ES_pcie_x16_@4x_name */ null,
	/* ES_pcie_x16_@4x_comment */ null,
	/* ES_pcie_x16_comment */ 'All PCI Express x16 slots conform to PCI Express 3.0 standard.',
	/* ES_pcie_x1_num */ 2,
	/* ES_pcie_x1_comment */ 'All PCI Express x1 slots conform to PCI Express 2.0 standard.',
	/* ES_pci_num */ null,
	/* Multi-Graphics Technology */ 'Support for 4-Way/3-Way/2-Way AMD CrossFireX™/NVIDIA SLI technology',
	/* OG_IGP_d-sub_port */ null,
	/* OG_IGP_dvi-d_port_num */ null,
	/* OG_IGP_dvi-d_port_max_res */ null,
	/* OG_IGP_dvi-d_port_comment */ null,
	/* OG_IGP_hdmi_port_num */ null,
	/* OG_IGP_hdmi_port_max_res */ null,
	/* OG_IGP_displayport_num */ null,
	/* OG_IGP_displayport_max_res */ null,
	/* OG_chip-2_name */ null,
	/* OG_chip-2_thunderbolt_port_num */ null,
	/* OG_chip-2_thunderbolt_port_ver */ null,
	/* OG_chip-2_thunderbolt_port_max_res */ null,
	/* OG_chip-2_thunderbolt_port_supp_mini-displayport */ null,
	/* OG_chip-2_thunderbolt_port_supp_thunderbolt_monitor(s) */ null,
	/* OG_chip-2_thunderbolt_port_comment */ null,
	/* SI_chip-1_sata_6Gb/s_connector_num */ 2,
	/* SI_chip-1_sata_6Gb/s_connector_ver */ 'SATA3.0/1',
	/* SI_chip-1_sata_6Gb/s_connector_upTo */ '2 SATA 6Gb/s devices',
	/* SI_chip-1_sata_3Gb/s_connector_num */ 4,
	/* SI_chip-1_sata_3Gb/s_connector_ver */ 'SATA2.2/5',
	/* SI_chip-1_sata_3Gb/s_connector_upTo */ '4 SATA 3Gb/s devices',
	/* SI_chip-1_raid_supp */ 'RAID 0, RAID 1, RAID 5, and RAID 10',
	/* SI_chip-1_raid_supp_comment */ 'When a RAID set is built across the SATA 6Gb/s and SATA 3Gb/s channels, the system performance of the RAID set may vary depending on the devices being connected.',
	/* SI_chip-1_sas_3Gb/s_connector_num */ null,
	/* SI_chip-1_sas_3Gb/s_connector_ver */ null,
	/* SI_chip-1_sas_3Gb/s_connector_upTo */ null,
	/* SI_chip-1_sas_3Gb/s_connector_raid_supp */ null,
	/* SI_chip-2 */ 'Marvell 88SE9172',
	/* SI_chip-2_sata_6Gb/s_connector_num */ 4,
	/* SI_chip-2_sata_6Gb/s_connector_ver */ 'SATA3.6/9',
	/* SI_chip-2_sata_6Gb/s_connector_upTo */ '4 SATA 6Gb/s devices',
	/* SI_chip-2_esata_6Gb/s_connector_num */ 2,
	/* SI_chip-2_esata_6Gb/s_connector_ver */ 'on the back panel',
	/* SI_chip-2_esata_6Gb/s_connector_upTo */ '2 SATA 6Gb/s devices',
	/* SI_chip-2_raid_supp */ 'RAID 0 and RAID 1',
	/* SI_chip-2_raid_supp_comment */ null,
	/* USB_chip-1_upTo */ 14,
	/* USB_chip-1_ver */ 'USB 2.0/1.1',
	/* USB_chip-1_ports on the back panel */ 8,
	/* USB_chip-1_ports available through the internal USB headers */ 6,
	/* USB_chip-2 */ 'Fresco FL1009',
	/* USB_chip-2_upTo */ 4,
	/* USB_chip-2_ver */ 'USB 3.0/2.0',
	/* USB_chip-2_ports on the back panel */ 2,
	/* USB_chip-2_ports available through the internal USB headers */ 2,
	/* USB_chip-3 */ null,
	/* USB_chip-3_upTo */ null,
	/* USB_chip-3_ver */ null,
	/* USB_chip-3_ports on the back panel */ null,
	/* USB_chip-3_ports available through the internal USB headers */ null,
	/* IEEE 1394_chip_name */ null,
	/* IEEE 1394_chip_upTo */ null,
	/* IEEE 1394_chip_ver */ null,
	/* IEEE 1394_chip_ports on the back panel */ null,
	/* IEEE 1394_chip_ports available through the internal header */ null,
	/* IIOC_24-pin ATX main power connector */ 1,
	/* IIOC_8-pin ATX 12V power connector */ 1,
	/* IIOC_4-pin ATX 12V power connector */ null,
	/* IIOC_PCIe power connector */ null,
	/* IIOC_SATA 6Gb/s connector */ 6,
	/* IIOC_SATA 3Gb/s connector */ 4,
	/* IIOC_mSATA connector */ null,
	/* IIOC_CPU fan header */ 1,
	/* IIOC_system fan header */ 4,
	/* IIOC_front panel header */ 1,
	/* IIOC_front panel audio header */ 1,
	/* IIOC_S/PDIF Out header */ 1,
	/* IIOC_USB 3.0/2.0 header */ 1,
	/* IIOC_USB 2.0/1.1 header */ 3,
	/* IIOC_IEEE 1394a header */ null,
	/* IIOC_serial port header */ 1,
	/* IIOC_parallel port */ null,
	/* IIOC_chassis intrusion header */ null,
	/* IIOC_digital microphone header */ null,
	/* IIOC_speaker header */ null,
	/* IIOC_AIO speaker header */ null,
	/* IIOC_LVDS drive voltage header */ null,
	/* IIOC_LVDS connector */ null,
	/* IIOC_flat panel display power header */ null,
	/* IIOC_flat panel display power connector */ null,
	/* IIOC_flat panel display switch header */ null,
	/* IIOC_backlight switch header */ null,
	/* IIOC_WIFI activity indicator LED header */ null,
	/* IIOC_Clear CMOS jumper */ 1,
	/* IIOC_Trusted Platform Module (TPM) header */ 1,
	/* IIOC_onboard voltage measurement module */ null,
	/* IIOC_Voltage Measurement Points */ null,
	/* IIOC_power button */ null,
	/* IIOC_reset button */ null,
	/* IIOC_Clear CMOS button */ null,
	/* IIOC_Gear button */ null,
	/* IIOC_CPU BCLK Down button */ null,
	/* IIOC_CPU BCLK Up button */ null,
	/* IIOC_CPU Ratio Down button */ null,
	/* IIOC_CPU Ratio Up button */ null,
	/* IIOC_BIOS Switch */ null,
	/* IIOC_LN2 switch */ null,
	/* BPC_PS/2 keyboard port */ null,
	/* BPC_PS/2 mouse port */ null,
	/* BPC_PS/2 keyboard/mouse port */ 1,
	/* BPC_CPU overclocking button */ null,
	/* BPC_BIOS switch button */ null,
	/* BPC_Clear CMOS button */ null,
	/* BPC_IEEE 1394 port */ null,
	/* BPC_IEEE 1394a port */ null,
	/* BPC_USB 3.0/2.0 port */ 2,
	/* BPC_USB 2.0/1.1 port */ 8,
	/* BPC_eSATA/USB Combo connector */ null,
	/* BPC_eSATA 6Gb/s connector */ 2,
	/* BPC_RJ-45 port */ 1,
	/* BPC_parallel port */ null,
	/* BPC_serial port */ null,
	/* BPC_optical S/PDIF Out connector */ 1,
	/* BPC_coaxial S/PDIF Out connector */ 1,
	/* BPC_DC-In power connector */ null,
	/* BPC_audio jacks */ 6,
	/* BPC_audio jacks_detail */ 'Center/Subwoofer Speaker Out/Rear Speaker Out/Side Speaker Out/Line In/Line Out/Microphone',
	/* BPC_D-Sub port */ null,
	/* BPC_DVI-D port */ null,
	/* BPC_HDMI port */ null,
	/* BPC_DisplayPort */ null,
	/* I/O Controller */ 'iTE I/O Controller Chip',
	/* HWM_System voltage detection */ 'YES',
	/* HWM_CPU/System temperature detection */ 'YES',
	/* HWM_CPU/System fan speed detection */ 'YES',
	/* HWM_CPU overheating warning */ 'YES',
	/* HWM_CPU/System fan fail warning */ 'YES',
	/* HWM_CPU/System fan speed control */ 'YES',
	/* HWM_comment */ 'Whether the CPU/system fan speed control function is supported will depend on the CPU/system cooler you install.',
	/* BIOS_detail_1 */ '2 x 64 Mbit flash',
	/* BIOS_detail_2 */ 'Use of licensed AMI EFI BIOS',
	/* BIOS_detail_3 */ 'Support for DualBIOS™',
	/* BIOS_detail_4 */ 'PnP 1.0a, DMI 2.0, SM BIOS 2.6, ACPI 2.0a',
	/* BIOS_detail_5 */ null,
	/* UF_supp_@BIOS */ 'YES',
	/* UF_supp_Q-Flash */ 'YES',
	/* UF_supp_Xpress BIOS Rescue */ null,
	/* UF_supp_Download Center */ null,
	/* UF_supp_Xpress Install */ 'YES',
	/* UF_supp_Xpress Recovery2 */ null,
	/* UF_supp_EasyTune */ 'YES',
	/* UF_supp_Smart 6™ */ null,
	/* UF_supp_eXtreme Hard Drive (X.H.D) */ null,
	/* UF_supp_ON/OFF Charge */ 'YES',
	/* UF_supp_Cloud OC */ null,
	/* UF_supp_3TB+ Unlock */ 'YES',
	/* UF_supp_TouchBIOS */ null,
	/* UF_supp_Q-Share */ 'YES',
	/* UF_supp_3D Power */ 'YES',
	/* UF_comment */ 'Available functions in EasyTune may differ by motherboard model.',
	/* Bundle Software */ 'Norton Internet Security (OEM version)',
	/* Operating System */ 'Microsoft® Windows 8/7/Vista/XP',
	/* Form Factor */ 'ATX Form Factor; 30.5cm x 24.4cm',
	/* Remark_1 */ "Due to different Linux support condition provided by chipset vendors, please download Linux driver from chipset vendors' website or 3rd party website.",
	/* Remark_2 */ "Most hardware/software vendors may no longer offer drivers to support Win9X/ME/2000/XP SP1/SP2. If drivers are available from the vendors, we will update them on the GIGABYTE website.",
	/* img_1 */ 'images/motherboard/GA-X79-UP4/1.jpg',
	/* img_2 */ null,
	/* img_3 */ null,
	/* img_4 */ null,
	/* img_5 */ null,
	/* img_6 */ null,
	/* img_7 */ null,
	/* img_8 */ null,
	/* img_9 */ null,
	/* img_10 */ null,
	/* img_brand */ 'images/motherboard/brand/GIGABYTE_Logo.png',
	/* price */ '990,000'
);

INSERT INTO motherboard VALUES (
	/* id */ null,
	/* company */ 'GIGABYTE',
	/* model */ 'GA-X79-UD3',
	/* rev */ 1.1,
	/* chipset */ 'Intel&reg; X79 Express Chipset',
	/* C_compnay */ 'Intel',
	/* C_socket */ '2011',
	/* C_supp_detail_1 */ 'Support for Intel&reg; Core&trade; i7 processors in the LGA2011 package package',
	/* C_supp_detail_2 */ 'L3 cache varies with CPU',
	/* C_supp_detail_3 */ null,
	/* C_supp_detail_4 */ null,
	/* C_supp_detail_5 */ null,
	/* M_ddr2_slot */ null,
	/* M_ddr2_upTo */ null,
	/* M_ddr2_bus */ null,
	/* M_ddr2_comment */ null,
	/* M_ddr3_slot */ 4,
	/* M_ddr3_upTo */ 32,
	/* M_ddr3_bus */ '2400/2133/1866/1600/1333/1066',
	/* M_ddr3_comment */ 'Due to Windows 32-bit operating system limitation, when more than 4 GB of physical memory is installed, the actual memory size displayed will be less than 4 GB.',
	/* M_upTo */ 32,
	/* M_architecture */ '4 channel',
	/* M_supp_unbuffered-ecc_memory_modules */ null,
	/* M_supp_non-ecc_memory_modules */ 'YES',
	/* M_supp_xmp_memory_modules */ 'YES',
	/* M_supp_xmp_memory_modules_comment */ null,
	/* A_chip */ 'Realtek ALC898 codec',
	/* A_channel */ '2/4/5.1/7.1',
	/* A_hd_audio */ null,
	/* A_supp_spdif_out */ 'YES',
	/* A_supp_dolby®_home_theater */ 'YES',
	/* A_supp_eax®_advanced_hd™_5.0 */ null,
	/* A_supp_x-fi_xtreme_fidelity® */ null,
	/* L_chip_1 */ 'Intel GbE LAN (10/100/1000 Mbit)',
	/* L_chip_2 */ null,
	/* Wireless Communication module_detail_1 */ null,
	/* Wireless Communication module_detail_2 */ null,
	/* ES_pcie_x16_@16x_num */ 2,
	/* ES_pcie_x16_@16x_name */ 'PCIEX16_1, PCIEX16_2',
	/* ES_pcie_x16_@16x_comment */ 'For optimum performance, if only one PCI Express graphics card is to be installed, be sure to install it in the PCIEX16 slot.',
	/* ES_pcie_x16_@8x_num */ 2,
	/* ES_pcie_x16_@8x_name */ 'PCIEX8_1, PCIEX8_2',
	/* ES_pcie_x16_@8x_comment */ 'The PCIEX8_2 slot shares bandwidth with the PCIEX16_2 slot. When the PCIEX8_2 slot is populated, the PCIEX16_2 slot will operate at up to x8 mode.',
	/* ES_pcie_x16_@4x_num */ null,
	/* ES_pcie_x16_@4x_name */ null,
	/* ES_pcie_x16_@4x_comment */ null,
	/* ES_pcie_x16_comment */ '(All PCI Express x16 slots conform to PCI Express 3.0 standard.)',
	/* ES_pcie_x1_num */ 2,
	/* ES_pcie_x1_comment */ '(All PCI Express x1 slots conform to PCI Express 2.0 standard.)',
	/* ES_pci_num */ 1,
	/* Multi-Graphics Technology */ 'Support for 4-Way/3-Way/2-Way AMD CrossFireX™/NVIDIA SLI technology.',
	/* OG_IGP_d-sub_port */ null,
	/* OG_IGP_dvi-d_port_num */ null,
	/* OG_IGP_dvi-d_port_max_res */ null,
	/* OG_IGP_dvi-d_port_comment */ null,
	/* OG_IGP_hdmi_port_num */ null,
	/* OG_IGP_hdmi_port_max_res */ null,
	/* OG_IGP_displayport_num */ null,
	/* OG_IGP_displayport_max_res */ null,
	/* OG_chip-2_name */ null,
	/* OG_chip-2_thunderbolt_port_num */ null,
	/* OG_chip-2_thunderbolt_port_ver */ null,
	/* OG_chip-2_thunderbolt_port_max_res */ null,
	/* OG_chip-2_thunderbolt_port_supp_mini-displayport */ null,
	/* OG_chip-2_thunderbolt_port_supp_thunderbolt_monitor(s) */ null,
	/* OG_chip-2_thunderbolt_port_comment */ null,
	/* SI_chip-1_sata_6Gb/s_connector_num */ 2,
	/* SI_chip-1_sata_6Gb/s_connector_ver */ 'SATA3.0/1',
	/* SI_chip-1_sata_6Gb/s_connector_upTo */ '2 SATA 6Gb/s devices',
	/* SI_chip-1_sata_3Gb/s_connector_num */ 4,
	/* SI_chip-1_sata_3Gb/s_connector_ver */ 'SATA2 2/3/4/5',
	/* SI_chip-1_sata_3Gb/s_connector_upTo */ '4 SATA 3Gb/s devices',
	/* SI_chip-1_raid_supp */ 'RAID 0, RAID 1, RAID 5, and RAID 10',
	/* SI_chip-1_raid_supp_comment */ 'When a RAID set is built across the SATA 6Gb/s and SATA 3Gb/s channels, the system performance of the RAID set may vary depending on the devices being connected.',
	/* SI_chip-1_sas_3Gb/s_connector_num */ null,
	/* SI_chip-1_sas_3Gb/s_connector_ver */ null,
	/* SI_chip-1_sas_3Gb/s_connector_upTo */ null,
	/* SI_chip-1_sas_3Gb/s_connector_raid_supp */ null,
	/* SI_chip-2 */ 'Marvell 88SE9172',
	/* SI_chip-2_sata_6Gb/s_connector_num */ 4,
	/* SI_chip-2_sata_6Gb/s_connector_ver */ 'GSATA3.6/7/8/9',
	/* SI_chip-2_sata_6Gb/s_connector_upTo */ '4 SATA 6Gb/s devices',
	/* SI_chip-2_esata_6Gb/s_connector_num */ 2,
	/* SI_chip-2_esata_6Gb/s_connector_ver */ 'on the back panel',
	/* SI_chip-2_esata_6Gb/s_connector_upTo */ '2 SATA 6Gb/s devices',
	/* SI_chip-2_raid_supp */ 'RAID 0 and RAID 1',
	/* SI_chip-2_raid_supp_comment */ null,
	/* USB_chip-1_upTo */ 14,
	/* USB_chip-1_ver */ 'USB 2.0/1.1',
	/* USB_chip-1_ports on the back panel */ 8,
	/* USB_chip-1_ports available through the internal USB headers */ 6,
	/* USB_chip-2 */ 'Fresco FL1009',
	/* USB_chip-2_upTo */ 4,
	/* USB_chip-2_ver */ 'USB 3.0/2.0',
	/* USB_chip-2_ports on the back panel */ 2,
	/* USB_chip-2_ports available through the internal USB headers */ 2,
	/* USB_chip-3 */ null,
	/* USB_chip-3_upTo */ null,
	/* USB_chip-3_ver */ null,
	/* USB_chip-3_ports on the back panel */ null,
	/* USB_chip-3_ports available through the internal USB headers */ null,
	/* IEEE 1394_chip_name */ null,
	/* IEEE 1394_chip_upTo */ null,
	/* IEEE 1394_chip_ver */ null,
	/* IEEE 1394_chip_ports on the back panel */ null,
	/* IEEE 1394_chip_ports available through the internal header */ null,
	/* IIOC_24-pin ATX main power connector */ 1,
	/* IIOC_8-pin ATX 12V power connector */ 1,
	/* IIOC_4-pin ATX 12V power connector */ null,
	/* IIOC_PCIe power connector */ null,
	/* IIOC_SATA 6Gb/s connector */ 6,
	/* IIOC_SATA 3Gb/s connector */ 4,
	/* IIOC_mSATA connector */ null,
	/* IIOC_CPU fan header */ 1,
	/* IIOC_system fan header */ 4,
	/* IIOC_front panel header */ 1,
	/* IIOC_front panel audio header */ 1,
	/* IIOC_S/PDIF Out header */ 1,
	/* IIOC_USB 3.0/2.0 header */ 1,
	/* IIOC_USB 2.0/1.1 header */ 3,
	/* IIOC_IEEE 1394a header */ null,
	/* IIOC_serial port header */ 1,
	/* IIOC_parallel port */ null,
	/* IIOC_chassis intrusion header */ null,
	/* IIOC_digital microphone header */ null,
	/* IIOC_speaker header */ null,
	/* IIOC_AIO speaker header */ null,
	/* IIOC_LVDS drive voltage header */ null,
	/* IIOC_LVDS connector */ null,
	/* IIOC_flat panel display power header */ null,
	/* IIOC_flat panel display power connector */ null,
	/* IIOC_flat panel display switch header */ null,
	/* IIOC_backlight switch header */ null,
	/* IIOC_WIFI activity indicator LED header */ null,
	/* IIOC_Clear CMOS jumper */ 1,
	/* IIOC_Trusted Platform Module (TPM) header */ 1,
	/* IIOC_onboard voltage measurement module */ null,
	/* IIOC_Voltage Measurement Points */ null,
	/* IIOC_power button */ null,
	/* IIOC_reset button */ null,
	/* IIOC_Clear CMOS button */ null,
	/* IIOC_Gear button */ null,
	/* IIOC_CPU BCLK Down button */ null,
	/* IIOC_CPU BCLK Up button */ null,
	/* IIOC_CPU Ratio Down button */ null,
	/* IIOC_CPU Ratio Up button */ null,
	/* IIOC_BIOS Switch */ null,
	/* IIOC_LN2 switch */ null,
	/* BPC_PS/2 keyboard port */ null,
	/* BPC_PS/2 mouse port */ null,
	/* BPC_PS/2 keyboard/mouse port */ 1,
	/* BPC_CPU overclocking button */ null,
	/* BPC_BIOS switch button */ null,
	/* BPC_Clear CMOS button */ null,
	/* BPC_IEEE 1394 port */ null,
	/* BPC_IEEE 1394a port */ null,
	/* BPC_USB 3.0/2.0 port */ 8,
	/* BPC_USB 2.0/1.1 port */ 2,
	/* BPC_eSATA/USB Combo connector */ null,
	/* BPC_eSATA 6Gb/s connector */ 2,
	/* BPC_RJ-45 port */ 1,
	/* BPC_parallel port */ null,
	/* BPC_serial port */ null,
	/* BPC_optical S/PDIF Out connector */ 1,
	/* BPC_coaxial S/PDIF Out connector */ 1,
	/* BPC_DC-In power connector */ null,
	/* BPC_audio jacks */ 6,
	/* BPC_audio jacks_detail */ 'Center/Subwoofer Speaker Out/Rear Speaker Out/Side Speaker Out/Line In/Line Out/Microphone',
	/* BPC_D-Sub port */ null,
	/* BPC_DVI-D port */ null,
	/* BPC_HDMI port */ null,
	/* BPC_DisplayPort */ null,
	/* I/O Controller */ 'iTE IT8728 chip',
	/* HWM_System voltage detection */ 'YES',
	/* HWM_CPU/System temperature detection */ 'YES',
	/* HWM_CPU/System fan speed detection */ 'YES',
	/* HWM_CPU overheating warning */ 'YES',
	/* HWM_CPU/System fan fail warning */ 'YES',
	/* HWM_CPU/System fan speed control */ 'YES',
	/* HWM_comment */ 'Whether the CPU/system fan speed control function is supported will depend on the CPU/system cooler you install',
	/* BIOS_detail_1 */ '2 x 64 Mbit flash',
	/* BIOS_detail_2 */ 'Use of licensed AMI EFI BIOS',
	/* BIOS_detail_3 */ 'Support for DualBIOS™',
	/* BIOS_detail_4 */ 'PnP 1.0a, DMI 2.0, SM BIOS 2.6, ACPI 2.0a',
	/* BIOS_detail_5 */ null,
	/* UF_supp_@BIOS */ 'YES',
	/* UF_supp_Q-Flash */ 'YES',
	/* UF_supp_Xpress BIOS Rescue */ 'YES',
	/* UF_supp_Download Center */ 'YES',
	/* UF_supp_Xpress Install */ 'YES',
	/* UF_supp_Xpress Recovery2 */ 'YES',
	/* UF_supp_EasyTune */ 'YES',
	/* UF_supp_Smart 6™ */ 'YES',
	/* UF_supp_eXtreme Hard Drive (X.H.D) */ 'YES',
	/* UF_supp_ON/OFF Charge */ 'YES',
	/* UF_supp_Cloud OC */ 'YES',
	/* UF_supp_3TB+ Unlock */ 'YES',
	/* UF_supp_TouchBIOS */ 'YES',
	/* UF_supp_Q-Share */ 'YES',
	/* UF_supp_3D Power */ null,
	/* UF_comment */ 'Available functions in EasyTune may differ by motherboard model.',
	/* Bundle Software */ 'Norton Internet Security (OEM version)',
	/* Operating System */ 'Microsoft® Windows 8/7/Vista/XP',
	/* Form Factor */ 'ATX Form Factor; 30.5cm x 24.4cm',
	/* Remark_1 */ "Due to different Linux support condition provided by chipset vendors, please download Linux driver from chipset vendor's website or 3rd party website.",
	/* Remark_2 */ "Most hardware/software vendors may no longer offer drivers to support Win9X/ME/2000/XP SP1/SP2. If drivers are available from the vendors, we will update them on the GIGABYTE website.",
	/* img_1 */ 'images/motherboard/GA-X79-UD3/1.jpg',
	/* img_2 */ 'images/motherboard/GA-X79-UD3/2.jpg',
	/* img_3 */ 'images/motherboard/GA-X79-UD3/3.jpg',
	/* img_4 */ 'images/motherboard/GA-X79-UD3/4.jpg',
	/* img_5 */ null,
	/* img_6 */ null,
	/* img_7 */ null,
	/* img_8 */ null,
	/* img_9 */ null,
	/* img_10 */ null,
	/* img_brand */ 'images/motherboard/brand/GIGABYTE_Logo.png',
	/* price */ '860,000'
);

INSERT INTO motherboard VALUES(
	/* id */ null,
	/* company */ 'GIGABYTE',
	/* model */ 'GA-X79-UD5',
	/* rev */ 1.0,
	/* chipset */ 'Intel&reg; X79 Express Chipset',
	/* C_compnay */ 'Intel',
	/* C_socket */ '2011',
	/* C_supp_detail_1 */ 'Support for Intel&reg; Core&trade; i7 processors in the LGA2011 package',
	/* C_supp_detail_2 */ 'L3 cache varies with CPU',
	/* C_supp_detail_3 */ null,
	/* C_supp_detail_4 */ null,
	/* C_supp_detail_5 */ null,
	/* M_ddr2_slot */ null,
	/* M_ddr2_upTo */ null,
	/* M_ddr2_bus */ null,
	/* M_ddr2_comment */ null,
	/* M_ddr3_slot */ 8,
	/* M_ddr3_upTo */ 64,
	/* M_ddr3_bus */ '2133/1866/1600/1333/1066',
	/* M_ddr3_comment */ 'Due to Windows 32-bit operating system limitation, when more than 4 GB of physical memory is installed, the actual memory size displayed will be less than 4 GB.',
	/* M_upTo */ 64,
	/* M_architecture */ '4 channel',
	/* M_supp_unbuffered-ecc_memory_modules */ null,
	/* M_supp_non-ecc_memory_modules */ 'YES',
	/* M_supp_xmp_memory_modules */ 'YES',
	/* M_supp_xmp_memory_modules_comment */ null,
	/* A_chip */ 'Realtek ALC898 codec',
	/* A_channel */ '2/4/5.1/7.1',
	/* A_hd_audio */ 'YES',
	/* A_supp_spdif_out */ 'YES',
	/* A_supp_dolby®_home_theater */ 'YES',
	/* A_supp_eax®_advanced_hd™_5.0 */ null,
	/* A_supp_x-fi_xtreme_fidelity® */ null,
	/* L_chip_1 */ 'Intel GbE LAN (10/100/1000 Mbit)',
	/* L_chip_2 */ null,
	/* Wireless Communication module_detail_1 */ 'Wi-Fi 802.11 b/g/n',
	/* Wireless Communication module_detail_2 */ 'Bluetooth 4.0, 3.0+HS, 2.1+EDR',
	/* ES_pcie_x16_@16x_num */ 2,
	/* ES_pcie_x16_@16x_name */ 'PCIEX16_1/PCIEX16_2',
	/* ES_pcie_x16_@16x_comment */ 'For optimum performance, if only one PCI Express graphics card is to be installed, be sure to install it in the PCIEX16_1 slot; if you are installing two PCI Express graphics cards, it is recommended that you install them in the PCIEX16_1 and PCIEX16_2 slots.',
	/* ES_pcie_x16_@8x_num */ 2,
	/* ES_pcie_x16_@8x_name */ 'PCIEX8',
	/* ES_pcie_x16_@8x_comment */ null,
	/* ES_pcie_x16_@4x_num */ null,
	/* ES_pcie_x16_@4x_name */ null,
	/* ES_pcie_x16_@4x_comment */ null,
	/* ES_pcie_x16_comment */ 'All PCI Express x16 slots conform to PCI Express 3.0 standard.',
	/* ES_pcie_x1_num */ 2,
	/* ES_pcie_x1_comment */ 'All PCI Express x1 slots conform to PCI Express 2.0 standard.',
	/* ES_pci_num */ 1,
	/* Multi-Graphics Technology */ 'Support for 3-Way/2-Way AMD CrossFireX™ / NVIDIA SLI technology.',
	/* OG_IGP_d-sub_port */ null,
	/* OG_IGP_dvi-d_port_num */ null,
	/* OG_IGP_dvi-d_port_max_res */ null,
	/* OG_IGP_dvi-d_port_comment */ null,
	/* OG_IGP_hdmi_port_num */ null,
	/* OG_IGP_hdmi_port_max_res */ null,
	/* OG_IGP_displayport_num */ null,
	/* OG_IGP_displayport_max_res */ null,
	/* OG_chip-2_name */ null,
	/* OG_chip-2_thunderbolt_port_num */ null,
	/* OG_chip-2_thunderbolt_port_ver */ null,
	/* OG_chip-2_thunderbolt_port_max_res */ null,
	/* OG_chip-2_thunderbolt_port_supp_mini-displayport */ null,
	/* OG_chip-2_thunderbolt_port_supp_thunderbolt_monitor(s) */ null,
	/* OG_chip-2_thunderbolt_port_comment */ null,
	/* SI_chip-1_sata_6Gb/s_connector_num */ 2,
	/* SI_chip-1_sata_6Gb/s_connector_ver */ 'SATA3.0/SATA3.1',
	/* SI_chip-1_sata_6Gb/s_connector_upTo */ '2 SATA 6Gb/s devices',
	/* SI_chip-1_sata_3Gb/s_connector_num */ 4,
	/* SI_chip-1_sata_3Gb/s_connector_ver */ 'SATA2.2/SATA2.5',
	/* SI_chip-1_sata_3Gb/s_connector_upTo */ '4 SATA 3Gb/s devices',
	/* SI_chip-1_raid_supp */ 'RAID 0, RAID 1, RAID 5, and RAID 10',
	/* SI_chip-1_raid_supp_comment */ 'When a RAID set is built across the SATA 6Gb/s and SATA 3Gb/s channels, the system performance of the RAID set may vary depending on the devices being connected.',
	/* SI_chip-1_sas_3Gb/s_connector_num */ null,
	/* SI_chip-1_sas_3Gb/s_connector_ver */ null,
	/* SI_chip-1_sas_3Gb/s_connector_upTo */ null,
	/* SI_chip-1_sas_3Gb/s_connector_raid_supp */ null,
	/* SI_chip-2 */ 'Marvell 88SE9172',
	/* SI_chip-2_sata_6Gb/s_connector_num */ 4,
	/* SI_chip-2_sata_6Gb/s_connector_ver */ 'GSATA3.6/GSATA3.9',
	/* SI_chip-2_sata_6Gb/s_connector_upTo */ '4 SATA 6Gb/s devices',
	/* SI_chip-2_esata_6Gb/s_connector_num */ 2,
	/* SI_chip-2_esata_6Gb/s_connector_ver */ '(including 1 eSATA/USB Combo) on the back panel',
	/* SI_chip-2_esata_6Gb/s_connector_upTo */ '2 SATA 6Gb/s devices',
	/* SI_chip-2_raid_supp */ 'RAID 0 and RAID 1',
	/* SI_chip-2_raid_supp_comment */ null,
	/* USB_chip-1_upTo */ 14,
	/* USB_chip-1_ver */ 'USB 2.0/1.1',
	/* USB_chip-1_ports on the back panel */ 8,
	/* USB_chip-1_ports available through the internal USB headers */ 6,
	/* USB_chip-2 */ 'Fresco FL1009',
	/* USB_chip-2_upTo */ 4,
	/* USB_chip-2_ver */ 'USB 3.0/2.0',
	/* USB_chip-2_ports on the back panel */ 2,
	/* USB_chip-2_ports available through the internal USB headers */ 2,
	/* USB_chip-3 */ null,
	/* USB_chip-3_upTo */ null,
	/* USB_chip-3_ver */ null,
	/* USB_chip-3_ports on the back panel */ null,
	/* USB_chip-3_ports available through the internal USB headers */ null,
	/* IEEE 1394_chip_name */ 'VT6308',
	/* IEEE 1394_chip_upTo */ 2,
	/* IEEE 1394_chip_ver */ '1394a',
	/* IEEE 1394_chip_ports on the back panel */ 1,
	/* IEEE 1394_chip_ports available through the internal header */ 1,
	/* IIOC_24-pin ATX main power connector */ 1,
	/* IIOC_8-pin ATX 12V power connector */ 1,
	/* IIOC_4-pin ATX 12V power connector */ null,
	/* IIOC_PCIe power connector */ null,
	/* IIOC_SATA 6Gb/s connector */ 6,
	/* IIOC_SATA 3Gb/s connector */ 4,
	/* IIOC_mSATA connector */ null,
	/* IIOC_CPU fan header */ 1,
	/* IIOC_system fan header */ 4,
	/* IIOC_front panel header */ 1,
	/* IIOC_front panel audio header */ 1,
	/* IIOC_S/PDIF Out header */ 1,
	/* IIOC_USB 3.0/2.0 header */ 1,
	/* IIOC_USB 2.0/1.1 header */ 3,
	/* IIOC_IEEE 1394a header */ 1,
	/* IIOC_serial port header */ null,
	/* IIOC_parallel port */ null,
	/* IIOC_chassis intrusion header */ null,
	/* IIOC_digital microphone header */ null,
	/* IIOC_speaker header */ null,
	/* IIOC_AIO speaker header */ null,
	/* IIOC_LVDS drive voltage header */ null,
	/* IIOC_LVDS connector */ null,
	/* IIOC_flat panel display power header */ null,
	/* IIOC_flat panel display power connector */ null,
	/* IIOC_flat panel display switch header */ null,
	/* IIOC_backlight switch header */ null,
	/* IIOC_WIFI activity indicator LED header */ null,
	/* IIOC_Clear CMOS jumper */ 1,
	/* IIOC_Trusted Platform Module (TPM) header */ 1,
	/* IIOC_onboard voltage measurement module */ null,
	/* IIOC_Voltage Measurement Points */ null,
	/* IIOC_power button */ null,
	/* IIOC_reset button */ null,
	/* IIOC_Clear CMOS button */ null,
	/* IIOC_Gear button */ null,
	/* IIOC_CPU BCLK Down button */ null,
	/* IIOC_CPU BCLK Up button */ null,
	/* IIOC_CPU Ratio Down button */ null,
	/* IIOC_CPU Ratio Up button */ null,
	/* IIOC_BIOS Switch */ null,
	/* IIOC_LN2 switch */ null,
	/* BPC_PS/2 keyboard port */ null,
	/* BPC_PS/2 mouse port */ null,
	/* BPC_PS/2 keyboard/mouse port */ 1,
	/* BPC_CPU overclocking button */ 1,
	/* BPC_BIOS switch button */ 1,
	/* BPC_Clear CMOS button */ 1,
	/* BPC_IEEE 1394 port */ 1,
	/* BPC_IEEE 1394a port */ null,
	/* BPC_USB 3.0/2.0 port */ 2,
	/* BPC_USB 2.0/1.1 port */ 7,
	/* BPC_eSATA/USB Combo connector */ 1,
	/* BPC_eSATA 6Gb/s connector */ 1,
	/* BPC_RJ-45 port */ 1,
	/* BPC_parallel port */ null,
	/* BPC_serial port */ null,
	/* BPC_optical S/PDIF Out connector */ 1,
	/* BPC_coaxial S/PDIF Out connector */ null,
	/* BPC_DC-In power connector */ null,
	/* BPC_audio jacks */ 5,
	/* BPC_audio jacks_detail */ 'Center/Subwoofer Speaker Out, Rear Speaker Out, Side Speaker Out, Line In/Mic In, Line Out',
	/* BPC_D-Sub port */ null,
	/* BPC_DVI-D port */ null,
	/* BPC_HDMI port */ null,
	/* BPC_DisplayPort */ null,
	/* I/O Controller */ 'iTE IT8728 chip',
	/* HWM_System voltage detection */ 'YES',
	/* HWM_CPU/System temperature detection */ 'YES',
	/* HWM_CPU/System fan speed detection */ 'YES',
	/* HWM_CPU overheating warning */ 'YES',
	/* HWM_CPU/System fan fail warning */ 'YES',
	/* HWM_CPU/System fan speed control */ 'YES',
	/* HWM_comment */ 'Whether the CPU/system fan speed control function is supported will depend on the CPU/system cooler you install.',
	/* BIOS_detail_1 */ '2 x 64 Mbit flash',
	/* BIOS_detail_2 */ 'Use of licensed AMI EFI BIOS',
	/* BIOS_detail_3 */ 'Support for DualBIOS™',
	/* BIOS_detail_4 */ 'PnP 1.0a, DMI 2.0, SM BIOS 2.6, ACPI 2.0a',
	/* BIOS_detail_5 */ null,
	/* UF_supp_@BIOS */ 'YES',
	/* UF_supp_Q-Flash */ 'YES',
	/* UF_supp_Xpress BIOS Rescue */ 'YES',
	/* UF_supp_Download Center */ 'YES',
	/* UF_supp_Xpress Install */ 'YES',
	/* UF_supp_Xpress Recovery2 */ 'YES',
	/* UF_supp_EasyTune */ 'YES',
	/* UF_supp_Smart 6™ */ 'YES',
	/* UF_supp_eXtreme Hard Drive (X.H.D) */ 'YES',
	/* UF_supp_ON/OFF Charge */ 'YES',
	/* UF_supp_Cloud OC */ 'YES',
	/* UF_supp_3TB+ Unlock */ 'YES',
	/* UF_supp_TouchBIOS */ 'YES',
	/* UF_supp_Q-Share */ 'YES',
	/* UF_supp_3D Power */ null,
	/* UF_comment */ 'Available functions in EasyTune may differ by motherboard model.',
	/* Bundle Software */ 'Norton Internet Security (OEM version)',
	/* Operating System */ 'Microsoft® Windows 8/7/Vista/XP',
	/* Form Factor */ 'E-ATX Form Factor; 30.5cm x 26.4cm',
	/* Remark_1 */ "Due to different Linux support condition provided by chipset vendors, please download Linux driver from chipset vendors' website or 3rd party website.",
	/* Remark_2 */ "Most hardware/software vendors may no longer offer drivers to support Win9X/ME/2000/XP SP1/SP2. If drivers are available from the vendors, we will update them on the GIGABYTE website.",
	/* img_1 */ 'images/motherboard/GA-X79-UD5/1.jpg',
	/* img_2 */ 'images/motherboard/GA-X79-UD5/2.jpg',
	/* img_3 */ 'images/motherboard/GA-X79-UD5/3.jpg',
	/* img_4 */ 'images/motherboard/GA-X79-UD5/4.jpg',
	/* img_5 */ null,
	/* img_6 */ null,
	/* img_7 */ null,
	/* img_8 */ null,
	/* img_9 */ null,
	/* img_10 */ null,
	/* img_brand */ 'images/motherboard/brand/GIGABYTE_Logo.png',
	/* price */ '960,000'
);